version: "3.9"

services:

  # mariadb-42:
  # 	build: requirements/mariadb
  # 	image: mariadb-42
  #   env_file:
  #     - .env
  # 	volumes:
  # 		- db-data:/var/lib/mysql
  # 	networks:
  # 		- wpsite
  # 	restart: always

  # wordpress-42:
  # 	depends_on:
  # 		- mariadb-42
  # 	build: requirements/wordpress
  # 	image: wordpress
  #   env_file:
  #     - .env
  # 	volumes:
  # 		- www-data:/var/www/html
  # 	networks:
  # 		- wpsite
  # 	restart: always

  nginx-42:
    # depends_on:
    # 	- wordpress-42
    build: requirements/nginx
    image: nginx-42
    env_file:
      - .env
    volumes:
      - www-data:/var/www/html
    networks:
      - wpsite
    ports:
      - 443:443
    restart: always


networks:
  wpsite:


volumes:

  db-data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/db-data'

  www-data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/www-data'