version: "3.9"

services:

  mariadb:
    build: requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wpsite
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: requirements/wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - www-data:/var/www/html
    networks:
      - wpsite
    restart: always

  nginx:
    depends_on:
      - wordpress
    build: requirements/nginx
    image: nginx
    env_file:
      - .env
    volumes:
      - www-data:/var/www/html
    networks:
      - wpsite
    ports:
      - 80:80
      - 443:443
    restart: always


networks:
  wpsite:


volumes:

  db-data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/db-data'

  www-data:
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/data/www-data'